### ISSUE TITLE
Picking work space folder each time

### ISSUE THREAD

**Issue by Vulpesdk** [lfurzewaddock/vscode-wsl-workspacefolder#7]
Hello
I have with pleasure used your little extension and it pretty much do exactly what I want. I do however find it quite annoying I have to pick the workspace each time I want to run my debugger, is there any simple solution to this? I have set the windows.name property but it doesn't seem to do anything.

Dear regards 
Rune

**Comment by lfurzewaddock** [comment]
Hi @Rune, is it possible for you to provide a minimal working example of your issue for me to test against?

You should just need to provide each project folder name with matching `.vscode/launch.json`, for each project in the 'multi-root workspace'. Also, I'll need the the 'multi-root workspace' `.code-workspace` file.

**Comment by Vulpesdk** [comment]
I have my full project here: 
[https://github.com/Vulpesdk/App-submission1]

I'm probably just not typing the correct name but I can't figure it out :)

**Comment by lfurzewaddock** [comment]
The closest I got to C/C++ was C# so please forgive my ignorance. However, my guess is your problem is due to the way the project is set-up, as it is a multi-root project with a `workspace.code-workspace` file, but it contains only one project.

If you deleted the `workspace.code-workspace` the extension would not ask to confirm which project folder to use as it would be a single-folder project. However, you would need to move the settings object to the `.vscdode/launch.json` file.

**Comment by Vulpesdk** [comment]
AHA! I got it now, VS code did not by itself add the name proberty to code-workspace! Now it works! :D 
Thanks!
